services:
  - type: web
    name: botbot-discord
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
    autoDeploy: true
    branch: main
    rootDir: .
    healthCheckPath: /health
